config/routes.rb
NewGloriasSite::Application.routes.draw do
  root 'therapies#home'
  resources :therapies

end

app/models/therapy.rb
class Therapy < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/therapies_controller.rb
class TherapiesController < ApplicationController

  def index
    @therapies = Therapy.all
  end

  def show
    @therapy = Therapy.find_by(name: "Gloria")
  end

  def new
    @therapy = Therapy.new
  end

  def edit
    @therapy = Therapy.find_by(name: "Gloria")
  end

  def create
    @therapy = Therapy.new(therapy_params)

    respond_to do |format|
      if @therapy.save
        format.html { redirect_to @therapy, notice: 'Therapist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @therapy }
      else
        format.html { render action: 'new' }
        format.json { render json: @therapy.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @therapy = Therapy.find(params[:id])
    respond_to do |format|
      if @therapy.update(therapy_params)
        format.html { redirect_to @therapy, notice: 'Therapist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @therapy.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @therapy.destroy
    respond_to do |format|
      format.html { redirect_to therapies_url }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def therapy_params
      params.require(:therapy).permit(:name, :therapy, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/therapies_helper.rb
module TherapiesHelper
end

app/views/layouts/_carousel.html.erb
<div class="carousel">
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1"></li>
          <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          <div class="item active">
            <%= image_tag("lotus.jpg", :class => "img-thumbnail", :alt => "lotus flower") %>
          </div>
          <div class="item">
            <%= image_tag("man.jpg", :class => "img-thumbnail", :alt => "man receiving craniosacral") %>
          </div>
          <div class="item">
            <%= image_tag("bamboo.jpg", :class => "img-thumbnail", :alt => "bamboo") %>
          </div>
          <div class="item">
            <%= image_tag("woman.jpg", :class => "img-thumbnail", :alt => "woman receiving craniosacral") %>
          </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div>
    </div>
</div>

app/views/layouts/_header.html.erb
<div>
  <div class="line"></div>
  <div class="title">
    <div class="name">
      <div class="flower">
        <%= image_tag("lotus2.jpg", :alt => "lotus flower") %>
      </div>
      <h1 class="gloria">Gloria Flores <p class="certificate">CST-D</p></h1>
      <h2 class="certification">Diplomate Certified</h2>
      <h2 class="cranio">Craniosacral Therapist</h2>
      <p class="health" >
        Spiritual Health Coach​ License -  #1263 <br />
        California State CMT - #23263 <br />
        Board Certified Holistic Health Practitioner <br />
      </p>
    </div>

    <div>
      <%= render :partial => 'layouts/carousel' %>
    </div>
    <div class="line1"></div>
  </div>

  
  <ul class="pagination">
    <li><%= link_to "Home", root_path, :class => "page" %></li>
    <li><%= link_to "About", therapies_path, :class => "page" %></li>
    <li><%= link_to "Treatment", new_therapy_path, :class => "page" %></li>
    <li><%= link_to "Learn More", edit_therapy_path(:therapy_id), :class => "page" %></li>
    <li><%= link_to "Visit Us", therapy_path(:therapy_id), :class => "page" %></li>
  </ul>

  <div class="line2"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewGloriasSite</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/therapies/edit.html.erb
<body class="body">
<%= render :partial => 'layouts/header' %>

<div class="info3">
    <h2 class="learn">Learn more - read an article</h2>
    <div class="articles">
        <div class="articles1">
            <h5 class="article-title">Articles by Gloria Flores published on SelfGrowth.com</h5>
            <ul class="selfgrowth">
                <li><a href="http://www.selfgrowth.com/articles/craniosacral-therapy-an-alternative-approach-for-autism">How CST Helps Autism</a></li>

                <li><a href='http://www.selfgrowth.com/articles/craniosacral-therapy-helps-ptsd'>Craniosacral Therapy Helps PTSD</a></li>

                <li><a href="http://www.selfgrowth.com/articles/craniosacral-therapy-helps-addadhd">CST Helps ADD/ADHD</a></li>

                <li><a href="http://www.selfgrowth.com/articles/craniosacral-therapy-supports-self-healing">CST Supports Self-Healing</a></li>
                
                <li><a href="http://www.selfgrowth.com/articles/craniosacral-therapy-heals-bodymindspirit">CST Heals Body-Mind-Spirit</a></li>
                
                <li><a href="http://www.selfgrowth.com/articles/the-healing-power-of-nurturing-touch">The Healing Power of the Human Touch</a></li>
            </ul>
        </div>

        <div class="articles2">
            <h5 class="article-title">Articles by Gloria Flores published on The Messenger</h5>
            <ul class="messenger">
                <li><a href="http://www.themessenger.info/content/articles/health-a-healing-2/health-practices/item/1711-your-body%E2%80%99s-wisdom">Your Body's Wisdom</a></li>

                <li><a href="http://www.themessenger.info/content/articles/health-a-healing-2/health-practices/item/1577-is-craniosacral-therapy-for-you?">Is Craniosacral Therapy for You?</a></li>

                <li><a href="http://www.themessenger.info/content/articles/health-a-healing-2/item/655-are-you-depressed?">Are you depressed?</a></li>
                
                <li><a href="http://www.themessenger.info/content/articles/health-a-healing-2/item/617-women-and-migraines">Women and Migraines</a></li>
            </ul>
        </div>
    </div>

    <br />
    
    <div class="cst-class">
        <h2 class="class">Learn more - take a class</h2>
        <h4>Craniosacral Therapy Classes:</h4>
        <h5>Upledger Institute Craniosacral Therapy Introduction (CSTI)</h5>
        <br />
        <p>
            This 12-hour,  2-day class is OPEN TO THE PUBLIC. The workshop explores the History of CranioSacral Therapy, and the Anatomy & Physiology of the CranioSacral System. Students will develop light-touch palpation skills, and learn a full-body evaluation and treatment protocol for working with the fascia and membrane systems. Students will learn powerful and effective techniques for helping both themselves and others. A Certificate of Completion will be issued to each student from the Upledger Institute, along with 12 Continuing Education Hours for professional licensing. The next workshop is scheduled for Saturday and Sunday, June 7 & 8, 2014 at <%= link_to 'Wellness Works', 'http://wellnessworksglendale.org/', :class => "yelp" %> in Glendale, CA. To request a flyer for this class please send a request on my 'Visit Us' page.
        </p>
    </div>
</div>

<p class="copyright">© 2013 by Gloria Flores, CST-D</p>

app/views/therapies/home.html.erb
<body class="body2">
<%= render :partial => 'layouts/header' %>
  
  <div class="info">
    <div class="expertise">
      <p>
        <h4 class="areas"><u><strong>Areas of expertise:</strong></u></h4> 
        <ul>
          <li>Stress Management </li> 
          <li>Chronic Pain Relief </li> 
          <li>TMJ & Teeth Grinding </li> 
          <li>Headaches & Migraines </li> 
          <li>Neck & Back Pain </li> 
          <li>PTSD </li> 
          <li>Car Accidents </li> 
          <li>Depression & Anxiety </li> 
        </ul>
      </p>

      <br />

      <p>
        FSHLB Health Coach Lic.# 1263 <br />
        NCBTMB Provider #452863-12 <br />
        CA State CMT #23263 <br />
      </p>  

      <br />
      <div>
        <%= image_tag("dipl._cert2.jpg", :class => "cst-cert",:alt => "CST-D Certification") %>
        <a href= 'http://www.iahp.com/'><%= image_tag("IAHP.jpg", :class => "iahp", :alt => "IAHP link") %></a><br />
      </div>
      
      <div> 
        <%= image_tag("credit_cards.jpg", :class => "credit", :alt => "Accepted Credit Cards") %>
      </div>

      <br />

      <p>
        <h5 class="place"><strong>Burbank Craniosacral Therapy</strong></h5>
        <p>
          10000 Riverside Dr., #17 <br />
          Toluca Lake, CA 91602 
        </p>
      </p>
      
      <br />

      <p>
        <span class="session"><strong>Session Price:</strong></span> One Hour - $100 <br />
        Package Rates Available
      </p>

      <br />

      <p>
        <span class="serving"><strong>Serving:</strong></span>  Burbank, Glendale, <br /> 
        Pasadena, Los Angeles, <br />
        North Hollywood and <br />
        the San Fernando Valley
      </p>

      <br />

      <div class="button">
        <%= link_to 'Make an Appointment', therapy_path(:therapy_id), class: "btn btn-default"%>
      </div>
    </div>

    <div class="main">
      <h2 class="info-title"><strong>Craniosacral Therapy</strong></h2>
      <p>
        Is Chronic Pain, Anxiety, or Stress disrupting your life? If you're ready to live the productive life you long for, Craniosacral Therapy can help!
      </p>

      <br />

      <p>
        Craniosacral Therapy is a unique whole-person approach to health and healing that is one of the most gentle, yet powerful forms of alternative treatment available. Car Accidents, Falls, and Impact Injuries respond increadibly well to this work. When applied shortly after an accident, it can prevent trauma from settling into the soft tissues of your body. For older injuries, it can release trauma from the body's connective tissue and nervous system. Session results are long-lasting, and in many cases permanent since changes come from your own system.
      </p>

      <br />
      
      <p>
        Craniosacral Therapy is a combination of physical, energy, and hands-on techniques. It naturally relaxes your nervous system, reducing stress hormone levels in your body. This helps activate your body's innate healing response, and creates ideal conditions for better self-awareness, self-acceptance, and connection to your potential for growth and change.
      </p>

      <br />

      <p>
        Session results are immediate for most of my clients. My clients report that their sessions leave them feeling blissfully relaxed, centered, refreshed, and better able to handle stress. Please read more of what my clients have to say about their experiences on my <b><%= link_to 'YELP', 'http://www.yelp.com/biz/burbank-craniosacral-therapy-toluca-lake', :class => "yelp" %></b> page.
      </p>

      <br />

      <p>
        <span class="mission"><strong>Mission Statement:</strong></span>  
        My professional mission is to support your body's health and wholeness. By supporting your body's internal wisdom to make the changes you're ready for, we allow space for changes to come from within. When changes come from within they are more easily integrated, and more likely to be permanent. I acknowledge the power and wisdom that everyone's body holds for self-healing. My therapeutic mission is to support you in creating the healthy life you desire!
      </p>

      <br />

      <p class="signed-by">Gloria Flores, CST-D</p>
    </div>
  </div>
</div>
      
<p class="copyright">© 2013 by Gloria Flores, CST-D</p>

app/views/therapies/index.html.erb
<body class="body3">
<%= render :partial => 'layouts/header' %>
  
<div class="info0">
    <div class="expertise1">
      <p>
        <h4 class="areas"><u><strong>Areas of expertise:</strong></u></h4> 
        <ul>
          <li>Stress Management </li> 
          <li>Chronic Pain Relief </li> 
          <li>TMJ & Teeth Grinding </li> 
          <li>Headaches & Migraines </li> 
          <li>Neck & Back Pain </li> 
          <li>PTSD </li> 
          <li>Car Accidents </li> 
          <li>Depression & Anxiety </li> 
        </ul>
      </p>  
    </div>

    <div class="index-main">
        <h2 class="main-title">About Gloria Flores, CST-D</h2>

        <div>
            <h3 class="CST-D">Gloria Flores, CST-D<h3> <br />
            <p class="qualified">
                ﻿Upledger Institute Diplomate Certified <br />Craniosacral Therapist and Teacher <br />
                Board Certified H.H.P.  (Holistic Health Practitioner) <br />
                FSHLB Licensed Spiritual Health Coach <br />
                California State Certified Massage Therapist <br />
            </p>
        </div>

        <br />

        <p>
            Gloria has studied Alternative Therapies for over 20 years, with the goal of learning ways to help people overcome physical and emotional pain. She considers herself a life-long student and constantly updates her skills and knowledge with continuing education classes.
        </p>
        
        <p>
            Her clinical experience includes working with people in Hospice Care, Nursing Homes, patients with Chronic Illnesses, and Military Veterans with Post Traumatic Stress Disorder (PTSD).
        </p>

        <p>
            Gloria is a published Alternative Medicine Author and Teacher. She teaches CranioSacral Therapy Continuing Education courses to healthcare professionals and the public. For a class schedule please see the 'Learn More' page of this website.
        </p>
 
        <br />

        <h2 class="licenses">Certifications/Licenses</h2>
        <div>
            <h5><b>Upledger Institute</b></h5>
            <p>
                Techniques and Diplomate Certified Craniosacral Therapist <br />
                Certified Teaching Assistant and Instructor/Workshop Presenter <br />
            </p>
        </div>

        <div>
            <h5><b>UCLA</b></h5>
            <p>
                HIPPA Certified Practitioner
            </p>
        </div>
 
        <div>
            <h5><b>National Certification Board for Therapeutic Massage & Bodywork</b></h5>
            <p>
                Certified Continuing Education Provider for Craniosacral Education #451863-12
            </p>
        </div>

        <div>
            <h5><b>State of California</b></h5>
            <p>
                Certified Massage Therapist #23263
            </p>
        </div>

        <div>
            <h5><b>Federation of Spiritual Health Coach License Board</b></h5>
            <p>
                Nationally Licensed Spiritual Health Coach #1263
            </p>
        </div>
    </div>
</div>

<p class="copyright">© 2013 by Gloria Flores, CST-D</p>

app/views/therapies/new.html.erb
<%= render :partial => 'layouts/header' %>

<div class="info1">

  <div class="testimonials">

    <div>
        <h3 class="testimonial">Testimonials</h3>
        <br />
        <p>
            “I decided to see Gloria for stress and anxiety that were causing me to suffer from constant migraines. After about four sessions, I was able to recognize when I begin to feel stress coming on and do techniques to relax myself. With ocassional  follow-up sessions with Gloria my migraines are gone.”
        </p>
        <span class="client"> - Natalie W. </span>

    </div>

    <br />
    <br />
    <br />

    <div>
        <p>
            “I had problems sleeping at night because of past trauma from my childhood. Craniosacral Therapy has helped me to get my obsessive thoughts under control, and now I sleep through the night - every night."
        </p>
        <span class="client"> - Elliot S. </span>
    </div>

    <br />
    <br />

    <h5 class="rates"><u><b>Rates</b></u></h5>
    <div>
        <p class="consult">Initial Consultation and Session:  $100.00</p>
        <ul>
            <li>Therapeutic Plan for course of Treatment</li>
            <li>Educational materials</li>
            <li>Referrals as appropriate</li>
        </ul>
        <p class="consult">Follow-Up Sessions: 1 hour - $100.00</p>
    </div>

    <br />

    <div class="button">
        <%= link_to 'Make an Appointment', therapy_path(:therapy_id), class: "btn btn-default"%>
    </div>
  </div>


  <div class="treatment">
    <h2 class="help">How Craniosacral Therapy Can Help You</h2>

    <div>
        <h5><b>What is the dollar cost of a month of medications? Or time off from work in needless pain?</b></h5>
        <p>
            What is the cost of a surgery, or time lost in a slow convalescence? Craniosacral Therapy may help you avoid surgery, hasten your recovery from a serious illness or injury, and reduce, or eventually eliminate costly medications. 
        </p>
    </div>

    <div>
        <h5><b>Insurance Coverage</b></h5>
        <p>
            Craniosacral Therapy is now recognized as an effective therapy in the field of Alternative and Complimentary Medicine. This means that your session may be covered by your medical insurance with a prescription from your primary care physician and/or approval from your insurance company. I can provide you with receipts for your sessions so that you can request reimbursement from your insurance company. 
        </p>
    </div>

    <div>
        <h5><b>To prepare for your session</b></h5>
        <p>
            Please plan to arrive a few minutes early for your first session in order to fill out required paperwork and spend time discussing the reason for your visit. We recommend that clients wear loose, comfortable clothing, since clients remain fully clothed during their session. 
        </p>
    </div>

    <br />

    <h2 class="help">What to Expect During & After Your Session</h2>

    <div>
        <h5><b>During your session</b></h5>
        <p>
            You may become deeply relaxed, or even fall asleep. Experiences are individual and may differ from one session to the next. Some people talk a great deal, recalling memories. Others experience sensations within their bodies, such as tingling, heat/cold, numbness, pulsations, warmth, streatching of tissues, or a feeling of better energy flow. Some people are not aware of feeling much of anything during the evaluation and treatment process. 
        </p>
    </div>

    <div>
        <h5><b>After your session</b></h5>
        <p>
            Immediately after your session most people feel blissfully relaxed. This is because as your nervous system relaxes during your session, endorphins are released. It is wise to listen to your body at this time, and give yourself some space to integrate the changes that were made. A reduction in pain or an increase in function and range of motion may happen immediately, or gradually happen over the next few days or weeks. Although Craniosacral Therapy is very gentle, the effects can be powerful. Some people may be aware of general aches and pains that 'come and go' for a few days after their session. Other people may feel emotions after their session. These sensations are temporary and a normal part of your body's healing process. 
        </p>
    </div>
  </div>


</div>

<p class="copyright">© 2013 by Gloria Flores, CST-D</p>

app/views/therapies/show.html.erb
<body class="body1">
<%= render :partial => 'layouts/header' %>

<div class="info2">
    <div class="map">
        <%= image_tag("map.png", :class => "map-img",:alt => "map of location") %>
    </div>
    <div class="office">
        <%= image_tag("office.jpg", :class => "office",:alt => "picture of office building") %>
    </div>
    <div>
        <h2 class="appointment">Make an Appointment</h2>

        <br />
        
        <div class="contact">
            <h5>Gloria Flores, CST-D</h5>
            <br />
            <p>
                Craniosacral Therapy <br />
                10000 Riverside Dr., #17 <br />
                Toluca Lake, CA 91602 <br />
            </p>
            <br />
            <p>
                Tel: 818-919-3363​ <br />
                Email: <a href="mailto:craniosacralcare@yahoo.com?subject=Appointment Information">craniosacralcare@yahoo.com</a>
            </p>
        </div>
    </div>
</div>

<p class="copyright">© 2013 by Gloria Flores, CST-D</p>